language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-frontend nooreldeensalah/udagram-frontend:latest
  - docker tag udagram-api-feed nooreldeensalah/udagram-api-feed:latest
  - docker tag udagram-api-user nooreldeensalah/udagram-api-user:latest
  - docker tag reverseproxy nooreldeensalah/reverseproxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push nooreldeensalah/udagram-frontend
  - docker push nooreldeensalah/udagram-api-feed
  - docker push nooreldeensalah/udagram-api-user
  - docker push nooreldeensalah/reverseproxy
