apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: udagram-frontend
  name: udagram-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-frontend
  template:
    metadata:
      labels:
        app: udagram-frontend
    spec:
      containers:
      - name: udagram-frontend
        image: nooreldeensalah/udagram-frontend:eks
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1000Mi"
            cpu: "250m"
          limits:
            memory: "2000Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
