apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: reverseproxy
 minReplicas: 2
 maxReplicas: 3
 targetCPUUtilizationPercentage: 80
